//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MC.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cities
    {
        public string ZipCode { get; set; }
        public string City { get; set; }
        public string CityType { get; set; }
        public string StateAbbr { get; set; }
        public Nullable<int> RateJurisdictionID { get; set; }
    }
}
