//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MC.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComboEntries
    {
        public string cboId { get; set; }
        public string cboEntry { get; set; }
        public string cboBehavior { get; set; }
        public int RowId { get; set; }
        public bool Internal { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public string EnteredBy { get; set; }
        public byte[] SysTimeStamp { get; set; }
    
        public virtual ComboIds ComboIds { get; set; }
    }
}
