//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MC.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComboIds
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ComboIds()
        {
            this.ComboEntries = new HashSet<ComboEntries>();
        }
    
        public string cboId { get; set; }
        public string cboDesc { get; set; }
        public int entryLength { get; set; }
        public string DefaultEntry { get; set; }
        public string BehaviorLabel { get; set; }
        public byte[] SysTimeStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComboEntries> ComboEntries { get; set; }
    }
}
