//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MC.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailType
    {
        public int RowId { get; set; }
        public string EmailName { get; set; }
        public string FromEmailType { get; set; }
        public string FromEmailOther { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public string LastModBy { get; set; }
        public Nullable<System.DateTime> LastModDate { get; set; }
        public bool IsActive { get; set; }
    }
}
