//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MC.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderMaster()
        {
            this.Borrowers = new HashSet<Borrowers>();
        }
    
        public int OrderNo { get; set; }
        public int OE_RowId { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public string EnteredBy { get; set; }
        public string EDIReferenceNo { get; set; }
        public string OrderSource { get; set; }
        public string OrderOrigination { get; set; }
        public int ClientId { get; set; }
        public bool HaveAddress { get; set; }
        public bool HaveZip { get; set; }
        public string StreetNo { get; set; }
        public string StreetName { get; set; }
        public string StreetName2 { get; set; }
        public string StreetType { get; set; }
        public string Address1 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string County { get; set; }
        public string LoanNo { get; set; }
        public Nullable<decimal> LoanAmount { get; set; }
        public string LoanType { get; set; }
        public bool Piggyback { get; set; }
        public Nullable<decimal> PiggybackLoanAmt { get; set; }
        public Nullable<decimal> SalesPrice { get; set; }
        public Nullable<decimal> EstimatedValue { get; set; }
        public bool ExternalLender { get; set; }
        public Nullable<int> LenderId { get; set; }
        public bool NonOwnerOccupied { get; set; }
        public Nullable<int> OwnerAddressId { get; set; }
        public string CountyCode { get; set; }
        public string ZipPlusFour { get; set; }
        public string LastModBy { get; set; }
        public System.DateTime LastModDate { get; set; }
        public byte[] SysTimeStamp { get; set; }
        public Nullable<decimal> InterestRate { get; set; }
        public Nullable<bool> Hide { get; set; }
        public string ClientOrderNo { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public string IntegrationTransaction { get; set; }
        public Nullable<int> IntegrationID { get; set; }
        public string FHACaseNo { get; set; }
        public string PropertyType { get; set; }
        public bool IsClosingRequestIndicator { get; set; }
        public string IntegrationClientId { get; set; }
        public Nullable<int> LoanCategory { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Borrowers> Borrowers { get; set; }
        public virtual Counties Counties { get; set; }
        public virtual States States { get; set; }
    }
}
