//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MC.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public string Code { get; set; }
        public string Service { get; set; }
        public string Category { get; set; }
        public string Group { get; set; }
        public string Description { get; set; }
        public bool Internal { get; set; }
        public bool Inactive { get; set; }
        public string Instructions { get; set; }
        public bool ALTA { get; set; }
        public bool COD { get; set; }
        public bool Recording { get; set; }
        public bool RecordingRequired { get; set; }
        public int GPMPercent { get; set; }
        public bool PiggyBack { get; set; }
        public bool Purchase { get; set; }
        public string UsageNotes { get; set; }
        public string GLAccount { get; set; }
        public string GLAccount2 { get; set; }
        public Nullable<int> HUDLine { get; set; }
        public string PayeeCode { get; set; }
        public string TaskCode { get; set; }
        public bool AccountingOnly { get; set; }
        public bool DefaultProduct { get; set; }
        public bool DefaultCls { get; set; }
        public bool DefaultClsPiggy { get; set; }
        public string ReportType { get; set; }
        public bool TSMainTab { get; set; }
        public bool TSCommitTab { get; set; }
        public bool TSFeesTab { get; set; }
        public bool TSTaxTab { get; set; }
        public bool TSDeedsTab { get; set; }
        public bool TSMtgsTab { get; set; }
        public bool TSLiensTab { get; set; }
        public bool TSLegalTab { get; set; }
        public bool TSReqsTab { get; set; }
        public bool TSExceptsTab { get; set; }
        public bool TSEnforceReqFields { get; set; }
        public bool IncludeEndorsements { get; set; }
        public System.DateTime LastModDate { get; set; }
        public string LastModBy { get; set; }
        public byte[] SysTimeStamp { get; set; }
        public Nullable<decimal> WeightPrice { get; set; }
        public Nullable<decimal> WeightTurnTime { get; set; }
        public Nullable<decimal> WeightQuality { get; set; }
        public bool Uninsured { get; set; }
        public string TitleEscrowCode { get; set; }
        public bool BPO { get; set; }
        public Nullable<bool> DisplayOnWeb { get; set; }
        public Nullable<bool> AutoAssign { get; set; }
        public Nullable<bool> AutoSend { get; set; }
        public Nullable<bool> TitleOnlyPropClsDate { get; set; }
        public Nullable<bool> DisplayOnDashboard { get; set; }
        public Nullable<bool> SendNewOrderMsg { get; set; }
        public Nullable<bool> ExcludeFromHUD { get; set; }
        public Nullable<bool> EClosingProd { get; set; }
        public string AssociatedECloseProd { get; set; }
        public Nullable<int> ARClientId { get; set; }
        public Nullable<bool> AllowLoanPolicyChange { get; set; }
        public Nullable<bool> AllowOwnerPolicyChange { get; set; }
        public Nullable<bool> ReissueAvailable { get; set; }
        public Nullable<bool> PolicyProduct { get; set; }
        public Nullable<bool> TitleDecision { get; set; }
        public string VendorAssignAs { get; set; }
        public string DefaultSearchType { get; set; }
        public Nullable<bool> IgnoreTitleClearance { get; set; }
        public bool IsSchedulingProduct { get; set; }
        public bool IsCEMA { get; set; }
        public bool ExcludeFromAutoHold { get; set; }
    }
}
