//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MC.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityFormControl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SecurityFormControl()
        {
            this.SecurityFormControlConfig = new HashSet<SecurityFormControlConfig>();
        }
    
        public int SecurityFormControlId { get; set; }
        public int SecurityFormId { get; set; }
        public string Name { get; set; }
        public int SecurityControlId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public bool Inactive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string LastModBy { get; set; }
        public Nullable<System.DateTime> LastModDate { get; set; }
    
        public virtual SecurityControl SecurityControl { get; set; }
        public virtual SecurityForm SecurityForm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SecurityFormControlConfig> SecurityFormControlConfig { get; set; }
    }
}
