//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MC.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZipCodes
    {
        public int Id { get; set; }
        public string ZipCode { get; set; }
        public string ZipCodeType { get; set; }
        public string CountyCode { get; set; }
        public string MSA { get; set; }
        public string AreaCode { get; set; }
        public string TimeZone { get; set; }
        public Nullable<int> GMTOffset { get; set; }
        public string DST { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
    }
}
