export class OrderSummary {
    constructor(
        public OrderNo: number = null,
        public ProductCode: string = "",

        public OpenedText: string = "Opened",
        public OpenedDate: string = null,
        public TitleCompleteText: string = "Title Complete",
        public TitleCompleteDate: string = null,
        public DepartmentalCompleteText: string = "Departmental Complete",
        public DepartmentalCompleteDate: string = null,
        public TitleClearedText: string = "Title Cleared",
        public TitleClearedDate: string = null,
        public TitleBillUpdateText: string = "Title Bill Update",
        public TitleBillUpdateDate: string = null,
        public DocumentRecordedText: string = "Document Recorded",
        public DocumentRecordedDate: string = null,
        public FinalPolicyIssuedText: string = "Final Policy Issued",
        public FinalPolicyIssuedDate: string = null,

        public MileStoneTrackerList: Array<any> = new Array<any>(),

        public OpenedItemText: string = "Opened - Order received",
        public OpenedItemStatus: string = "Complete",
        public OpenedItemDate: string = null,
        public TitleItemText: string = "Title - Data being collected and Underwritten",
        public TitleItemStatus: string = "In-progress",
        public TitleItemDate: string = null,
        public DepartmentalItemText: string = "Departmental - Data being collected for review",
        public DepartmentalItemStatus: string = "In-progress",
        public DepartmentalItemDate: string = null,
        public CollateralItemText: string = "Collateral - Documents being collected for review",
        public CollateralItemStatus: string = "In-progress",
        public CollateralItemDate: string = null,
        public AttorneyItemText: string = "Attorney Clear to Close - Attorney ready to schedule",
        public AttorneyItemStatus: string = "In-progress",
        public AttorneyItemDate: string = null,
        public MortgageConnectItemText: string = "Mortgage Connect Clear to Close - Title Company Ready to Schedule",
        public MortgageConnectItemStatus: string = "In-progress",
        public MortgageConnectItemDate: string = null,
        public TitleBillItemText: string = "Title Bill - Title Fees Prepared",
        public TitleBillItemStatus: string = "In-progress",
        public TitleBillItemDate: string = null,
        public RecordingItemText: string = "Recording - Recordable Documents of Record",
        public RecordingItemStatus: string = "In-progress",
        public RecordingItemDate: string = null,
        public PolicyItemText: string = "Policy - Final Policy Issued",
        public PolicyItemStatus: string = "In-progress",
        public PolicyItemDate: string = null,
        public TitleUpdateItemText: string = "Title Update - Update of Title Report",
        public TitleUpdateItemStatus: string = "In-progress",
        public TitleUpdateItemDate: string = null,

        public ItemCheckList: Array<any> = new Array<any>()
    ) { }
}